import json

with open("seat_matrix_data_v1_baseline.json", "r", encoding="utf-8") as f:
    orig = json.load(f)

# Let's see how many colleges in orig for each Annexure
orig_ann = {}
for c in orig["colleges"]:
    orig_ann[c["annexure"]] = orig_ann.get(c["annexure"], 0) + 1
print("Original colleges by Annexure:", orig_ann)

# Let's read the seat_matrix_data.json generated by our new extract_seats_v2
with open("seat_matrix_data.json", "r", encoding="utf-8") as f:
    new_data = json.load(f)

new_ann = {}
for c in new_data["colleges"]:
    new_ann[c["annexure"]] = new_ann.get(c["annexure"], 0) + 1
print("New colleges by Annexure:", new_ann)
